name: Link Notion Task on GitHub Issue Create

on:
  issues:
    types: [opened]

jobs:
  link-notion-task:
    runs-on: ubuntu-latest

    steps:
      - name: Extract TS Task ID from Issue title/body
        id: extract
        run: |
          MATCH=$(echo "${{ github.event.issue.title }} ${{ github.event.issue.body }}" | grep -oE 'TS-[0-9]+')
          if [ -z "$MATCH" ]; then
            echo "No TS Task ID found"
            exit 0
          fi
          echo "TS_TASK_ID=$MATCH" >> $GITHUB_ENV
          echo "Found TS Task ID: $MATCH"

      - name: Query Notion for Task
        run: |
          curl -X POST "https://api.notion.com/v1/databases/${{ secrets.NOTION_DATABASE_ID }}/query" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            --data "{
              \"filter\": {
                \"property\": \"Name\",
                \"title\": {\"contains\": \"$TS_TASK_ID\"}
              }
            }" > notion_result.json

          PAGE_ID=$(jq -r '.results[0].id' notion_result.json)

          if [ "$PAGE_ID" != "null" ]; then
            ISSUE_URL="${{ github.event.issue.html_url }}"
            curl -X PATCH "https://api.notion.com/v1/pages/$PAGE_ID" \
              -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
              -H "Notion-Version: 2022-06-28" \
              -H "Content-Type: application/json" \
              --data "{
                \"properties\": {
                  \"git-issue\": {
                    \"rich_text\": [
                      {\"text\": {\"content\": \"$ISSUE_URL\"}}
                    ]
                  }
                }
              }"
            echo "Linked Notion Task $TS_TASK_ID with $ISSUE_URL"
          else
            echo "No matching Notion Task found for $TS_TASK_ID"
          fi
