name: Link Notion Task on GitHub Issue Create

on:
  issues:
    types: [opened]

jobs:
  link-notion-task:
    runs-on: ubuntu-latest

    steps:
      # 1. 이슈의 제목과 본문에서 'TS-숫자' 형식의 태스크 ID를 추출합니다.
      - name: Extract TS Task ID from Issue title/body
        id: extract
        run: |
          MATCH=$(echo "${{ github.event.issue.title }} ${{ github.event.issue.body }}" | grep -oE 'TS-[0-9]+')
          
          if [ -z "$MATCH" ]; then
            echo "No TS Task ID found in issue."
            exit 0
          fi
          
          echo "TS_TASK_ID=$MATCH" >> $GITHUB_ENV
          echo "Found TS Task ID: $MATCH"

      # 2. Notion API를 호출하여 태스크 ID에 해당하는 페이지를 찾아 이슈 URL을 업데이트합니다.
      - name: Link Issue to Notion Task
        run: |
          # Notion 데이터베이스에서 태스크 ID를 포함하는 페이지를 검색합니다.
          QUERY_RESULT=$(curl -s -X POST "https://api.notion.com/v1/databases/${{ secrets.NOTION_DATABASE_ID }}/query" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            --data "{
              \"filter\": {
                \"property\": \"Name\",
                \"title\": {
                  \"contains\": \"${{ env.TS_TASK_ID }}\"
                }
              }
            }")

          # 검색 결과에서 페이지 ID를 추출합니다.
          PAGE_ID=$(echo $QUERY_RESULT | jq -r '.results[0].id')

          # 페이지 ID가 존재하고 null이 아닐 경우에만 업데이트를 진행합니다.
          if [ "$PAGE_ID" != "null" ]; then
            ISSUE_URL="${{ github.event.issue.html_url }}"
            echo "Linking issue $ISSUE_URL to Notion page: $PAGE_ID"
            
            # 'git-issue' 속성을 URL 타입으로 업데이트합니다.
            curl -s -X PATCH "https://api.notion.com/v1/pages/$PAGE_ID" \
              -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
              -H "Notion-Version: 2022-06-28" \
              -H "Content-Type: application/json" \
              --data "{
                \"properties\": {
                  \"git-issue\": {
                    \"url\": \"$ISSUE_URL\"
                  }
                }
              }"
            echo "Successfully linked Notion task ${{ env.TS_TASK_ID }} with issue $ISSUE_URL."
          else
            echo "No matching Notion Task found for ${{ env.TS_TASK_ID }}."
          fi